# Generated by Django 5.2.4 on 2025-08-16 16:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTSPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Full Transparency', help_text='Main heading shown above the intro', max_length=120)),
                ('intro_body', wagtail.fields.RichTextField(blank=True, help_text='Introductory paragraph under the heading')),
                ('slices', wagtail.fields.StreamField([('section', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section subtitle', 'max_length': 150, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Paragraph text', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional supporting image', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image left'), ('right', 'Image right'), ('full', 'Image full width')], 'help_text': 'How to place the image relative to the text', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor id (e.g., 'research-ethics')", 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('subtitle', 0), ('body', 1), ('image', 2), ('image_position', 3), ('anchor', 4)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
