# Generated by Django 5.2.4 on 2025-08-23 12:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behind_scenes', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTSIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_heading', models.CharField(blank=True, default='Behind the Scenes', max_length=120)),
                ('intro_body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='btspage',
            name='category',
            field=models.CharField(choices=[('written', 'Written'), ('audio', 'Audio'), ('video', 'Video')], default='written', help_text='Which main category this BTS relates to.', max_length=20),
        ),
        migrations.AddField(
            model_name='btspage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, help_text='Optional image for teaser cards.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='btspage',
            name='teaser_summary',
            field=models.CharField(blank=True, help_text='1–2 lines max shown on cards. If empty, a truncation of the intro/body is used.', max_length=220),
        ),
        migrations.AddField(
            model_name='btspage',
            name='teaser_title',
            field=models.CharField(blank=True, help_text='Optional short title for teaser cards. Falls back to page title.', max_length=120),
        ),
    ]
