# Generated by Django 5.2.4 on 2025-08-24 14:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behind_scenes', '0003_remove_btspage_slices_btspage_body_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btspage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 4), ('embed', 5), ('gallery', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width'), ('left', 'Left'), ('right', 'Right')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alignment', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube / Vimeo / SoundCloud / Spotify, etc.'}), 6: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {'icon': 'image', 'label': 'Gallery image'}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('items', 7)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='btspage',
            name='category',
            field=models.CharField(choices=[('written', 'Written'), ('audio', 'Audio'), ('video', 'Video')], default='written', help_text='Which main section this BTS relates to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='btspage',
            name='intro_body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Intro paragraph under the heading.'),
        ),
        migrations.AlterField(
            model_name='btspage',
            name='intro_title',
            field=models.CharField(blank=True, help_text='Optional heading on detail page (falls back to page title).', max_length=120),
        ),
        migrations.AlterField(
            model_name='btspage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, help_text='Card/hero image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='btspage',
            name='teaser_summary',
            field=models.CharField(blank=True, help_text='1–2 lines for teaser cards.', max_length=220),
        ),
    ]
