# Generated by Django 5.2.4 on 2025-08-24 14:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behind_scenes', '0004_alter_btspage_body_alter_btspage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btspage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 4), ('embed', 5), ('gallery', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width'), ('left', 'Left'), ('right', 'Right')], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alignment', 3)]], {'icon': 'image', 'label': 'Image'}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'YouTube/Vimeo/SoundCloud/Spotify, etc.'}), 6: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {'icon': 'image', 'label': 'Gallery image'}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('items', 7)]], {'icon': 'image', 'label': 'Gallery'})}, null=True),
        ),
        migrations.AlterField(
            model_name='btspage',
            name='intro_title',
            field=models.CharField(blank=True, help_text='Optional heading on the detail page (falls back to page title).', max_length=120),
        ),
    ]
