# Generated by Django 5.2.4 on 2025-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behind_scenes', '0005_alter_btspage_body_alter_btspage_intro_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btspage',
            name='category',
            field=models.CharField(choices=[('written', 'Written'), ('audio', 'Audio'), ('video', 'Video'), ('communication', 'Communication')], default='written', help_text='Which main section this BTS relates to.', max_length=20),
        ),
    ]
