# Generated by Django 5.2.4 on 2025-08-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_with_me', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workwithmepage',
            old_name='thank_you_text',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='workwithmepage',
            old_name='portrait_image',
            new_name='portrait',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='contact_heading',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='email_display',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='form_heading',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='greeting_title',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='intro_body',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='intro_heading',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='phone_display',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='workwithmepage',
            name='to_address',
        ),
        migrations.AddField(
            model_name='workwithmepage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='workwithmepage',
            name='greeting',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workwithmepage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='WorkWithMeFormField',
        ),
    ]
