# Generated by Django 5.2.4 on 2025-08-18 16:35

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_with_me', '0003_workwithmepage_from_address_workwithmepage_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workwithmepage',
            name='bold_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workwithmepage',
            name='paragraph',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
