# Generated by Django 5.2.4 on 2025-08-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_with_me', '0004_workwithmepage_bold_text_workwithmepage_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='workwithmepage',
            name='qr_data',
            field=models.CharField(blank=True, help_text='Text/URL to encode. Leave blank to auto-use mailto:contact_email', max_length=300),
        ),
        migrations.AddField(
            model_name='workwithmepage',
            name='qr_scale',
            field=models.PositiveSmallIntegerField(default=10, help_text='Size scale for the QR SVG (higher = bigger)'),
        ),
    ]
