# Generated by Django 5.2.4 on 2025-08-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_with_me', '0005_workwithmepage_qr_data_workwithmepage_qr_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workwithmepage',
            name='qr_scale',
            field=models.PositiveSmallIntegerField(default=10, help_text='Size scale for the QR SVG'),
        ),
    ]
