# Generated by Django 5.2.4 on 2025-08-25 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('work_with_me', '0006_alter_workwithmepage_qr_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='workwithmepage',
            name='vcard_document',
            field=models.ForeignKey(blank=True, help_text='Upload a .vcf (vCard). The file contents will auto-fill the QR payload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='workwithmepage',
            name='qr_data',
            field=models.TextField(blank=True, help_text='Raw QR payload (vCard/URL/mailto/tel). If blank, will auto-generate.'),
        ),
    ]
