# Generated by Django 5.2.4 on 2025-08-25 16:39

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_with_me', '0007_workwithmepage_vcard_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workwithmepage',
            name='vcard_document',
        ),
        migrations.AddField(
            model_name='workwithmepage',
            name='vcard_file',
            field=models.FileField(blank=True, help_text='Upload a .vcf (vCard). The file contents will auto-fill the QR payload.', null=True, upload_to='vcards/'),
        ),
        migrations.AlterField(
            model_name='workwithmepage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
