# Generated by Django 5.2.4 on 2025-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_with_me', '0008_remove_workwithmepage_vcard_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workwithmepage',
            name='qr_data',
            field=models.TextField(blank=True, help_text='Raw QR payload (URL / mailto: / tel: / vCard text). Leave blank to auto-generate.'),
        ),
        migrations.AlterField(
            model_name='workwithmepage',
            name='vcard_file',
            field=models.FileField(blank=True, help_text='Upload a .vcf (vCard). QR will link to this file if present.', null=True, upload_to='vcards/'),
        ),
    ]
