# Generated by Django 5.2.4 on 2025-08-16 15:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('services', wagtail.fields.StreamField([('service', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor id (e.g. 'event-moderation')", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Service offering title', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Service description / details', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Header image for this service', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5), ('image', 6), ('link_label', 7), ('link_url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Examples / Projects', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Output / Task'}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Outputs / tasks you deliver', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('slug', 0), ('title', 1), ('details', 2), ('image', 3), ('examples', 10), ('outputs', 12)]], {})}, null=True)),
                ('project_highlights', wagtail.fields.StreamField([('highlight', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('link_label', 3), ('link_url', 4)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
