# Generated by Django 5.2.4 on 2025-12-02 19:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_communicationpage_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationpage',
            name='project_highlights',
            field=wagtail.fields.StreamField([('highlight', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('link_label', 3), ('link_url', 4)]], {})}, help_text='Optional highlights row at the end (e.g. Techfestival, OpenNext).', null=True),
        ),
        migrations.AlterField(
            model_name='communicationpage',
            name='services',
            field=wagtail.fields.StreamField([('service', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor id (e.g. 'event-planning'). If left blank, the title will be slugified.", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Service offering title (optional)', 'max_length': 120, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Service description / background', 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'What you actually offer under this service', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image for this service (shown under the Offering section)', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('image', 7), ('link_label', 8), ('link_url', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'Examples / projects for this service', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Output / Task'}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Outputs / tasks you deliver under this service', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('slug', 0), ('title', 1), ('details', 2), ('offering', 3), ('image', 4), ('examples', 11), ('outputs', 13)]], {})}, help_text='Add, remove or reorder services.', null=True),
        ),
    ]
