# Generated by Django 5.2.4 on 2025-12-02 19:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_communicationpage_project_highlights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationpage',
            name='services',
            field=wagtail.fields.StreamField([('service', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor id (e.g. 'event-planning'). If left blank, the title will be slugified.", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Service offering title (optional)', 'max_length': 120, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Service description / background', 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'What you actually offer under this service', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image for this service (shown under the Offering section)', 'required': False}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Example or case description for this service', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Outputs / results you deliver; can include bullet lists', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('slug', 0), ('title', 1), ('details', 2), ('offering', 3), ('image', 4), ('example', 5), ('output', 6)]], {})}, help_text='Add, remove or reorder services.', null=True),
        ),
    ]
