# Generated by Django 5.2.4 on 2025-12-02 20:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_alter_communicationpage_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationpage',
            name='instagram_reels',
            field=wagtail.fields.StreamField([('video', 1)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste any embed code (iframe, blockquote, script) OR a direct URL (Instagram / YouTube / Vimeo / TikTok, etc.).', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('embed_code', 0)]], {})}, help_text='Optional embedded videos (Instagram, YouTube, Vimeo, TikTok, etc.) shown at the bottom.', null=True),
        ),
    ]
