# Generated by Django 5.2.4 on 2026-03-09 12:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_communicationpage_instagram_reels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationpage',
            name='instagram_reels',
            field=wagtail.fields.StreamField([('video', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste a direct URL (Instagram / YouTube / Vimeo / TikTok, etc.) or embed code if needed.', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional preview image / thumbnail for Instagram or video cards.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short label shown under the preview.', 'max_length': 120, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('embed_code', 0), ('preview_image', 1), ('title', 2)]], {})}, help_text='Optional embedded videos (Instagram, YouTube, Vimeo, TikTok, etc.) shown at the bottom.', null=True),
        ),
        migrations.AlterField(
            model_name='communicationpage',
            name='services',
            field=wagtail.fields.StreamField([('service', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional anchor id (e.g. 'event-planning'). If left blank, the title will be slugified.", 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Service offering title (optional).', 'max_length': 120, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Service description / background.', 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'What you offer under this service.', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image for this service (shown under the Offering section).', 'required': False}), 5: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Example or case description for this service.', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Outputs / results you deliver; can include bullet lists.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('slug', 0), ('title', 1), ('details', 2), ('offering', 3), ('image', 4), ('example', 5), ('output', 6)]], {})}, help_text='Add, remove, or reorder services.', null=True),
        ),
    ]
