# Generated by Django 5.2.4 on 2026-03-09 13:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_communicationpage_instagram_reels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationpage',
            name='instagram_reels',
            field=wagtail.fields.StreamField([('instagram_card', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'help_text': 'Paste the clean Instagram post or reel URL.', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload a preview image or screenshot for the Instagram post.', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short title shown under the preview.', 'max_length': 120, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('url', 0), ('preview_image', 1), ('title', 2)]], {})}, help_text='Optional Instagram cards shown at the bottom.', null=True),
        ),
    ]
