# Generated by Django 5.2.4 on 2025-07-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_image_homepage_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='image',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='intro',
            new_name='hero_text',
        ),
    ]
