# Generated by Django 5.2.4 on 2025-08-16 12:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_hero_text_homepage_intro_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mission_statement',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
