# Generated by Django 5.2.4 on 2025-08-16 12:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_mission_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Header image for this service', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Service name', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2)]], {})}, null=True),
        ),
    ]
