# Generated by Django 5.2.4 on 2025-08-16 13:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='reviews',
            field=wagtail.fields.StreamField([('review', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Reviewer’s name', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Reviewer’s role / company', 'max_length': 150, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'The testimonial text', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional reviewer photo', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('quote', 2), ('image', 3)]], {})}, null=True),
        ),
    ]
