# Generated by Django 5.2.4 on 2025-10-06 09:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Header image for this service', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Service name', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description', 'required': True}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page to open', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL (used only if no internal page)', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional section ID on the target page (without #).', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('link_page', 3), ('link_url', 4), ('anchor', 5)]], {})}, null=True),
        ),
    ]
