# Generated by Django 5.2.4 on 2026-03-09 12:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about',
            field=wagtail.fields.StreamField([('about_item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section title', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Details for this section', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1)]], {})}, null=True),
        ),
    ]
