# Generated by Django 5.2.4 on 2025-08-16 17:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('episodes', wagtail.fields.StreamField([('episode', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'required': False}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste the episode embed URL (Spotify, SoundCloud, etc.)', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link to a Behind the Scenes section/page', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Behind the scenes', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('page', 5), ('label', 6)]], {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('date', 1), ('embed', 2), ('image', 3), ('teaser', 4), ('behind_scenes', 7)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('videos', wagtail.fields.StreamField([('video', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'required': False}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste the video URL (YouTube, Vimeo, Instagram reel link, etc.)', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional cover image (used if embed has no thumbnail)', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('auto', 'Auto'), ('landscape', 'Landscape'), ('portrait', 'Portrait')], 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link to a Behind the Scenes section/page', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Behind the scenes', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('page', 6), ('label', 7)]], {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('date', 1), ('embed', 2), ('image', 3), ('orientation', 4), ('teaser', 5), ('behind_scenes', 8)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WrittenPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('articles', wagtail.fields.StreamField([('article', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Outlet / publication name', 'max_length': 120, 'required': False}), 2: ('wagtail.blocks.DateBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Public link to the article', 'required': True}), 4: ('wagtail.blocks.TextBlock', (), {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional link to a Behind the Scenes section/page', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Behind the scenes', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('page', 6), ('label', 7)]], {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('publication', 1), ('date', 2), ('url', 3), ('teaser', 4), ('image', 5), ('behind_scenes', 8)]], {})}, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
