# Generated by Django 5.2.4 on 2025-08-17 09:12

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behind_scenes', '0001_initial'),
        ('journalism', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WrittenArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_name', models.CharField(blank=True, help_text='e.g. The Sun', max_length=150)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, help_text='If set, the index links out to this URL.')),
                ('excerpt', models.TextField(blank=True)),
                ('related_bts', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='related_articles', to='behind_scenes.btspage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
