# Generated by Django 5.2.4 on 2025-08-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalism', '0002_writtenindexpage_writtenarticlepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='writtenpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AudioPage',
        ),
        migrations.DeleteModel(
            name='VideoPage',
        ),
        migrations.DeleteModel(
            name='WrittenPage',
        ),
    ]
