# Generated by Django 5.2.4 on 2025-08-18 12:06

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behind_scenes', '0001_initial'),
        ('journalism', '0003_remove_videopage_page_ptr_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('video_date', models.DateField(blank=True, null=True)),
                ('standfirst', models.CharField(blank=True, max_length=180)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('embed_url', models.URLField(help_text='YouTube/Vimeo URL (oEmbed).')),
                ('produced_by', models.CharField(blank=True, max_length=120)),
                ('produced_for', models.CharField(blank=True, max_length=120)),
                ('external_url', models.URLField(blank=True, help_text='If set, index links out.')),
                ('related_bts', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='related_videos', to='behind_scenes.btspage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
