# Generated by Django 5.2.4 on 2025-08-23 12:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalism', '0004_videoindexpage_videopage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('episodes', wagtail.fields.StreamField([('episode', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'required': False}), 2: ('wagtail.blocks.RawHTMLBlock', (), {'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['behind_scenes.BTSPage'], 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Behind the Scenes', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('page', 4), ('label', 5)]], {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('date', 1), ('embed', 2), ('teaser', 3), ('behind_scenes', 6)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='writtenarticlepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='writtenarticlepage',
            name='related_bts',
        ),
        migrations.AddField(
            model_name='videoindexpage',
            name='videos',
            field=wagtail.fields.StreamField([('video', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.DateBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube/Vimeo URL (oEmbed)', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link out (e.g., YouTube watch page)', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('video_date', 1), ('embed_url', 2), ('standfirst', 3), ('description', 4), ('produced_by', 5), ('produced_for', 5), ('external_url', 6)]], {})}),
        ),
        migrations.AddField(
            model_name='writtenindexpage',
            name='articles',
            field=wagtail.fields.StreamField([('article', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.DateBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Destination URL', 'required': True}), 4: ('wagtail.blocks.TextBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('publication_name', 1), ('publication_date', 2), ('external_url', 3), ('excerpt', 4)]], {})}),
        ),
        migrations.DeleteModel(
            name='VideoPage',
        ),
        migrations.DeleteModel(
            name='WrittenArticlePage',
        ),
    ]
