# Generated by Django 5.2.4 on 2025-08-23 13:31

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalism', '0005_audiopage_remove_writtenarticlepage_page_ptr_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WrittenPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='writtenindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='audiopage',
            name='episodes',
        ),
        migrations.CreateModel(
            name='AudioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('audio_date', models.DateField(blank=True, null=True)),
                ('standfirst', models.CharField(blank=True, max_length=180)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('embed_url', models.URLField(help_text='SoundCloud/Spotify/etc. URL (oEmbed).')),
                ('produced_by', models.CharField(blank=True, max_length=120)),
                ('produced_for', models.CharField(blank=True, max_length=120)),
                ('external_url', models.URLField(blank=True, help_text='If set, buttons link out to this URL.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='journalism.audiopage')),
            ],
            options={
                'ordering': ['-audio_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('video_date', models.DateField(blank=True, null=True)),
                ('standfirst', models.CharField(blank=True, max_length=180)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('embed_url', models.URLField(help_text='YouTube/Vimeo URL (oEmbed).')),
                ('produced_by', models.CharField(blank=True, max_length=120)),
                ('produced_for', models.CharField(blank=True, max_length=120)),
                ('external_url', models.URLField(blank=True, help_text='If set, index links out.')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='journalism.videopage')),
            ],
            options={
                'ordering': ['-video_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WrittenArticleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('publication_name', models.CharField(blank=True, help_text='e.g. The Sun', max_length=150)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, help_text='If set, the index links out to this URL.')),
                ('excerpt', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='journalism.writtenpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='VideoIndexPage',
        ),
        migrations.DeleteModel(
            name='WrittenIndexPage',
        ),
    ]
