# Generated by Django 5.2.4 on 2025-08-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalism', '0007_writtenarticlepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WrittenArticlePage',
        ),
    ]
